=== DenislavVelichkov/Software_Engineering_State_Exam/past exams/2014/Solutions/2014-07-15/8/AddressBook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="names">
        <xs:sequence>
            <xs:element name="First" type="xs:string" />
            <xs:element name="Middle" type="xs:string" />
            <xs:element name="Last" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="address">
        <xs:sequence>
            <xs:element name="City" type="xs:string" />
            <xs:element name="Street">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="number" use="required" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="Postal-Code" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="telephone-numbers">
        <xs:sequence>
            <xs:element name="Mobile" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Home" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Contact">
        <xs:sequence>
            <xs:element name="Names" type="names" />
            <xs:element name="Address" type="address" />
            <xs:element name="Date-of-Birth" type="xs:string" />
            <xs:element name="Telephone-Numbers" type="telephone-numbers" />
        </xs:sequence>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="relative" />
                    <xs:enumeration value="colleague" />
                    <xs:enumeration value="acquaintance" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="Addressbook">
        <xs:sequence>
            <xs:element name="Contact" type="Contact" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Addressbook" type="Addressbook" />
</xs:schema>

=== DenislavVelichkov/Software_Engineering_State_Exam/past exams/2014/Solutions/2014-07-15/8/AddressBook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE Phonebook SYSTEM "AddressBook.xml">-->
<Addressbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="AddressBook.xsd">
    <Contact type="relative">
        <Names>
            <First>Pesho</First>
            <Middle>Goshov</Middle>
            <Last>Goshov</Last>
        </Names>
        <Address>
            <City>Sofia</City>
            <Street number="8">Random street</Street>
            <Postal-Code>1157</Postal-Code>
        </Address>
        <Date-of-Birth>25.02.1990</Date-of-Birth>
        <Telephone-Numbers>
            <Home>2456746543256</Home>
        </Telephone-Numbers>
    </Contact>
    <Contact type="colleague">
        <Names>
            <First>Tosho</First>
            <Middle>Toshev</Middle>
            <Last>Toshev</Last>
        </Names>
        <Address>
            <City>Sofia</City>
            <Street number="10">Random street</Street>
            <Postal-Code>0022</Postal-Code>
        </Address>
        <Date-of-Birth>15.12.1970</Date-of-Birth>
        <Telephone-Numbers>
            <Mobile>43156457654</Mobile>
        </Telephone-Numbers>
    </Contact>
    <Contact type="relative">
        <Names>
            <First>Gosho</First>
            <Middle>Peshev</Middle>
            <Last>Peshev</Last>
        </Names>
        <Address>
            <City>Sofia</City>
            <Street number="20">Random street</Street>
            <Postal-Code>0011</Postal-Code>
        </Address>
        <Date-of-Birth>21.9.1980</Date-of-Birth>
        <Telephone-Numbers>
            <Mobile>35465654654</Mobile>
            <Home>246476542342</Home>
        </Telephone-Numbers>
    </Contact>
    <Contact type="acquaintance">
        <Names>
            <First>Bai Ivan</First>
            <Middle>Ivanov</Middle>
            <Last>Ivanov</Last>
        </Names>
        <Address>
            <City>Sofia</City>
            <Street number="30">Random street</Street>
            <Postal-Code>2233</Postal-Code>
        </Address>
        <Date-of-Birth>3.3.1960</Date-of-Birth>
        <Telephone-Numbers></Telephone-Numbers>
    </Contact>
</Addressbook>
